### ISSUE TITLE
[Public Catalog] Display the Documentation details for packs under the "Data source" tab

### ISSUE THREAD

**Issue by rudouglas** [newrelic/developer-website#1516]
## Description
Once the `Data source` tab is added to a pack as part of #1511 , if any new `documentation` info is available populate that data in the tab. This data should come from the `config.yml` e.g.:

```
documentation:
  - name: AWS RDS installation docs
    description: This is the description
    url: https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-rds-monitoring-integration
```

This should be a Tile component showing the 
 - `name` parameter as title of the tile
 - `description` field as other content in the tile
 - Link to the `url` when clicked. 

In future packs may have multiple references to documentation, so ensure that we account for this when displaying content in the tab.

**NOTE: the design image shows this tile under `Overview` tab, but it should be under `Data sources`**

<img width="419" alt="Screenshot 2021-08-16 at 14 07 20" src="https://user-images.githubusercontent.com/17122543/129568495-0f82fc1b-9489-46a5-a57f-3182b1a62ff6.png">

## Acceptance Criteria 

- [x] Populate the `Data sources` tab with the documentation reference defined in the pack.
- [x] Support multiple documentation links for packs with many doc references.
