### ISSUE TITLE
Review how the OSS Team's URL Linter works and determine how we can use it on the DevSite

### ISSUE THREAD

**Issue by jpvajda** [newrelic/developer-website#430]
### User Story 

The OSS team has shared a solution they put in place for their terraform docs for checking broken links via static analysis without the need to spin up an instance of the site. 

There’s a github action we used to get it going: https://github.com/newrelic/terraform-provider-newrelic/blob/master/.github/workflows/test.yml#L40-L47
.github/workflows/test.yml:40-47

```
    - name: Check links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.markdownlinkcheck.json'
        folder-path: 'website/docs'
        file-extension: '.markdown'
```

https://github.com/newrelic/terraform-provider-newrelic/blob/master/.markdownlinkcheck.json

```
.markdownlinkcheck.json
{
    "ignorePatterns": [
        {
            "pattern": "^http(s)?://(?!(github.com|(www\\.)?terraform\\.io))"
        }
```
https://github.com/gaurav-nelson/github-action-markdown-link-check
gaurav-nelson/github-action-markdown-link-check
